// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStatus'](arg1, arg2, arg3);
}

export function WindowGetPosition() {
  return window['go']['main']['App']['WindowGetPosition']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowSetPosition(arg1, arg2) {
  return window['go']['main']['App']['WindowSetPosition'](arg1, arg2);
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
