// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow():Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateStatus(arg1:string,arg2:string,arg3:string):Promise<any>;

export function WindowGetPosition():Promise<number|number>;

export function WindowMinimize():Promise<void>;

export function WindowSetPosition(arg1:number,arg2:number):Promise<void>;

export function WindowToggleMaximize():Promise<void>;
